export const testimonialsData = [
  {
    name: 'Priya S.',
    location: 'Mumbai, India',
    label: 'Stock Investor',
    feedback: 'PriductAI\'s stock predictions are spot-on. I\'ve seen a 25% return in just 6 months. Highly recommended for any serious stock investor!',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman investor',
  },
  {
    name: 'Raj K.',
    location: 'Bengaluru, India',
    label: 'Crypto Analyst',
    feedback: 'The crypto insights are invaluable. The platform helped me navigate the volatile market with confidence and avoid major losses.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man professional',
  },
  {
    name: 'Anita D.',
    location: 'Delhi, India',
    label: 'Forex Trader',
    feedback: 'Real-time data and AI analysis for currency pairs are top-notch. It\'s my go-to platform for forex trading.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'person happy',
  },
  {
    name: 'John Smith',
    location: 'New York, USA',
    label: 'Stock Investor',
    feedback: 'As a US-based investor, I find the global market coverage exceptional. The AI predictions have consistently outperformed my expectations.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'male trader',
  },
  {
    name: 'Emily Chen',
    location: 'London, UK',
    label: 'Commodities Trader',
    feedback: 'The forecasts for gold and oil are incredibly accurate. This tool has become an essential part of my trading strategy.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman commodities trader',
  },
  {
    name: 'Suresh P.',
    location: 'Chennai, India',
    label: 'Beginner Investor',
    feedback: 'The learning hub is fantastic! I went from knowing nothing to making my first profitable trade in just a month.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'young student',
  },
  {
    name: 'Fatima Al Jaber',
    location: 'Dubai, UAE',
    label: 'Wealth Manager',
    feedback: 'I use PriductAI to complement my research for clients. The AI-driven insights add a valuable layer of data to my analysis.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'wealth manager professional',
  },
  {
    name: 'Kenji Tanaka',
    location: 'Tokyo, Japan',
    label: 'Crypto Enthusiast',
    feedback: 'Amazing tool for tracking altcoins and DeFi projects. The predictions helped me discover hidden gems in the crypto space.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man crypto japan',
  },
  {
    name: 'Aarav M.',
    location: 'Pune, India',
    label: 'Stock Investor',
    feedback: 'The user interface is so intuitive and easy to use. I can find all the information I need in one place.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.6,
    imageHint: 'man on laptop',
  },
  {
    name: 'Isabelle Dubois',
    location: 'Paris, France',
    label: 'Forex Trader',
    feedback: 'The platform\'s analysis of EUR/USD is consistently reliable. A must-have for any serious forex trader.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'woman at desk',
  },
  {
    name: 'Vikram N.',
    location: 'Hyderabad, India',
    label: 'IPO Investor',
    feedback: 'The IPO analysis is thorough and insightful. It helped me make a great decision on a recent listing.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'investor meeting',
  },
  {
    name: 'Chloe Lim',
    location: 'Singapore',
    label: 'Stock Investor',
    feedback: 'I appreciate the focus on both Indian and international markets. It gives me a broader perspective on my investments.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'woman singapore',
  },
  {
    name: 'Rohan G.',
    location: 'Kolkata, India',
    label: 'Crypto Analyst',
    feedback: 'The AI predictions are a game-changer. Finally, a tool that brings data science to crypto trading for everyone.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'man smiling',
  },
  {
    name: 'Maria Garcia',
    location: 'Madrid, Spain',
    label: 'Financial Advisor',
    feedback: 'PriductAI is a powerful tool for demonstrating market trends to my clients. The visuals are clear and compelling.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'financial advisor woman',
  },
  {
    name: 'Siddharth B.',
    location: 'Ahmedabad, India',
    label: 'Commodities Trader',
    feedback: 'I trade agricultural commodities, and the insights provided by PriductAI have been surprisingly accurate.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.6,
    imageHint: 'man at farm',
  },
  {
    name: 'Olivia Wilson',
    location: 'Sydney, Australia',
    label: 'Stock Investor',
    feedback: 'The 24/7 support is excellent. I had a query about a feature, and the team responded within minutes.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'customer support friendly',
  },
  {
    name: 'Aditya V.',
    location: 'Jaipur, India',
    label: 'Forex Trader',
    feedback: 'The combination of technical indicators and AI predictions gives me a real edge in the market.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'trader with charts',
  },
  {
    name: 'Lucas Müller',
    location: 'Berlin, Germany',
    label: 'Tech Investor',
    feedback: 'As someone focused on tech stocks, the detailed analysis of companies like Apple and Tesla is exactly what I need.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man tech office',
  },
  {
    name: 'Ananya R.',
    location: 'Surat, India',
    label: 'Crypto Analyst',
    feedback: 'The platform simplifies complex crypto concepts, making it accessible for analysts at all levels.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'woman working late',
  },
  {
    name: 'David Lee',
    location: 'Toronto, Canada',
    label: 'Stock Investor',
    feedback: 'I\'ve been investing for 20 years, and PriductAI is one of the most innovative tools I\'ve come across.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'senior investor',
  },
  {
    name: 'Zara Baig',
    location: 'Karachi, Pakistan',
    label: 'Stock Investor',
    feedback: 'A reliable and powerful platform. The market intelligence reports are particularly useful for my strategy.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'woman in office',
  },
  {
    name: 'Alexei Ivanov',
    location: 'Moscow, Russia',
    label: 'Commodities Trader',
    feedback: 'The predictions on energy commodities have been very helpful for my trading in a volatile market.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'man serious look',
  },
  {
    name: 'Nisha P.',
    location: 'Kochi, India',
    label: 'Forex Trader',
    feedback: 'I started with a small account and have steadily grown it thanks to the insights from PriductAI. Thank you!',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman happy casual',
  },
  {
    name: 'Daniel Kim',
    location: 'Seoul, South Korea',
    label: 'Crypto Analyst',
    feedback: 'The sentiment analysis feature is unique and provides a great overview of the market mood.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man korean',
  },
  {
    name: 'Chen Wei',
    location: 'Shanghai, China',
    label: 'Stock Investor',
    feedback: 'Excellent analysis of the Asian markets. The platform is fast, responsive, and packed with features.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man asian business',
  },
  {
    name: 'Meera K.',
    location: 'Indore, India',
    label: 'Beginner Investor',
    feedback: 'The mobile app is fantastic! I can track my portfolio and get predictions on the go.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman with phone',
  },
  {
    name: 'Javier Rodriguez',
    location: 'Mexico City, Mexico',
    label: 'Stock Investor',
    feedback: 'I trust the data and the AI. It\'s a refreshing change from all the noise and hype in financial media.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man relaxed',
  },
  {
    name: 'Lakshmi M.',
    location: 'Visakhapatnam, India',
    label: 'IPO Investor',
    feedback: 'Being able to research and apply for IPOs in one place is a huge time-saver. The analysis is spot-on.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'woman professional smiling',
  },
  {
    name: 'Mohammed Al-Farsi',
    location: 'Riyadh, Saudi Arabia',
    label: 'Crypto Analyst',
    feedback: 'A truly global platform. The insights into the crypto market are relevant no matter where you are in the world.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man middle east',
  },
  {
    name: 'Arjun T.',
    location: 'Nagpur, India',
    label: 'Stock Investor',
    feedback: 'The expert support feature is amazing. I booked a consultation and got personalized advice that was incredibly helpful.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'man in video call',
  },
  {
    name: 'Sofia Rossi',
    location: 'Rome, Italy',
    label: 'Forex Trader',
    feedback: 'The platform has a clean design and is very user-friendly, even with all its advanced features.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'woman stylish',
  },
  {
    name: 'Riya S.',
    location: 'Chandigarh, India',
    label: 'Stock Investor',
    feedback: 'The predictions have helped me build a more resilient and profitable portfolio. I couldn\'t be happier with the results.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman happy background',
  },
  {
    name: 'Liam Murphy',
    location: 'Dublin, Ireland',
    label: 'Crypto Analyst',
    feedback: 'Great community and support. It\'s more than just a tool; it\'s a network of smart investors.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man friendly',
  },
  {
    name: 'Alok J.',
    location: 'Bhopal, India',
    label: 'Commodities Trader',
    feedback: 'Finally, a platform that gives commodities the attention they deserve. The data is comprehensive and reliable.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'man thinking',
  },
  {
    name: 'Graceful Okoro',
    location: 'Lagos, Nigeria',
    label: 'Forex Trader',
    feedback: 'The AI-powered alerts save me so much time. I can act quickly on market movements without being glued to the screen.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman african business',
  },
  {
    name: 'Prakash R.',
    location: 'Lucknow, India',
    label: 'Stock Investor',
    feedback: 'I was skeptical about AI in trading, but PriductAI has made me a believer. The accuracy is impressive.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man happy arms crossed',
  },
  {
    name: 'Gabriela Silva',
    location: 'São Paulo, Brazil',
    label: 'Stock Investor',
    feedback: 'An excellent tool for tracking both local and international stocks. The platform is fast and never disappoints.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'woman brazil',
  },
  {
    name: 'Imran C.',
    location: 'Coimbatore, India',
    label: 'Crypto Analyst',
    feedback: 'The real-time market snapshots are perfect for a quick overview before I start my day. Incredibly useful.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'man with coffee',
  },
  {
    name: 'Hassan Ali',
    location: 'Cairo, Egypt',
    label: 'Stock Investor',
    feedback: 'A very professional and trustworthy platform. The educational resources have been a great help in my journey.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man egypt',
  },
  {
    name: 'Deepak S.',
    location: 'Patna, India',
    label: 'Forex Trader',
    feedback: 'The premium membership is worth every penny. The advanced tools have taken my trading to the next level.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'man confident',
  },
  {
    name: 'Anika Reddy',
    location: 'San Francisco, USA',
    label: 'Tech Investor',
    feedback: 'The AI predictions on emerging tech stocks are invaluable. Helped me get in early on several winners.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman tech professional',
  },
  {
    name: 'Omar Abdullah',
    location: 'Kuala Lumpur, Malaysia',
    label: 'Crypto Analyst',
    feedback: 'One of the best crypto analysis tools out there. The data visualizations make complex trends easy to understand.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man malaysia',
  },
  {
    name: 'Pooja T.',
    location: 'Guwahati, India',
    label: 'Beginner Investor',
    feedback: 'I feel so much more confident about investing now. The platform is empowering and easy to navigate.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman smiling bright',
  },
  {
    name: 'Leo Van Der Berg',
    location: 'Amsterdam, Netherlands',
    label: 'Stock Investor',
    feedback: 'Excellent customer service and a rock-solid platform. The team is clearly passionate about what they do.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man netherlands',
  },
  {
    name: 'Ishaan M.',
    location: 'Vadodara, India',
    label: 'Stock Investor',
    feedback: 'The market intelligence reports are detailed and save me hours of research time. A fantastic feature.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.7,
    imageHint: 'man reading report',
  },
  {
    name: 'Aisha Khan',
    location: 'Dhaka, Bangladesh',
    label: 'Forex Trader',
    feedback: 'I use PriductAI daily for my forex analysis. It\'s reliable, fast, and the predictions are consistently accurate.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'woman bangladesh',
  },
  {
    name: 'Mustafa Elgohary',
    location: 'Alexandria, Egypt',
    label: 'Crypto Analyst',
    feedback: 'The AI-driven risk assessment is a lifesaver in the crypto market. It helps me manage my positions effectively.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man with glasses',
  },
  {
    name: 'Kavita R.',
    location: 'Mysore, India',
    label: 'Stock Investor',
    feedback: 'From Nifty 50 to Nasdaq, the coverage is fantastic. A truly comprehensive tool for the modern investor.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 5,
    imageHint: 'woman professional',
  },
  {
    name: 'Jakub Nowak',
    location: 'Warsaw, Poland',
    label: 'Stock Investor',
    feedback: 'The platform is great value for money. The insights you get are worth far more than the subscription fee.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.9,
    imageHint: 'man poland',
  },
  {
    name: 'Sunil G.',
    location: 'Ranchi, India',
    label: 'Commodities Trader',
    feedback: 'Tracking gold and silver has never been easier. The live data and AI forecasts are essential for my daily trades.',
    photoUrl: 'https://placehold.co/112x112.png',
    rating: 4.8,
    imageHint: 'man trader serious',
  },
];
